name: Run Tests
on: [push, pull_request]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.6.8
        poetry_version: 0.12.17
        working_directory: ./
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.6.8
        poetry_version: 0.12.17
        working_directory: ./
        args: run python -m pytest tests/
